apiVersion: pipeline.knative.dev/v1alpha1
kind: PipelineResource
metadata:
  name: simple-git-source
spec:
  type: git
  params:
  - name: revision
    value: master
  - name: url
    value: https://github.com/mnuttall/simple

---

apiVersion: pipeline.knative.dev/v1alpha1
kind: PipelineResource
metadata:
  name: simple-image-resource
spec:        
  type: image
  params:
  - name: url
    value: host.docker.internal:5000/mnuttall/simple-from-pipeline
